/**
 * Uber API
 * Move your app forward with the Uber API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Activities from './model/Activities';
import Activity from './model/Activity';
import Error from './model/Error';
import PriceEstimate from './model/PriceEstimate';
import Product from './model/Product';
import ProductList from './model/ProductList';
import Profile from './model/Profile';
import ProductsApi from './api/ProductsApi';


/**
* Move_your_app_forward_with_the_Uber_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var UberApi = require('interface/index'); // See note below*.
* var xxxSvc = new UberApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new UberApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['interface/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new UberApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new UberApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module interface/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:interface/ApiClient}
     */
    ApiClient,

    /**
     * The Activities model constructor.
     * @property {module:interface/model/Activities}
     */
    Activities,

    /**
     * The Activity model constructor.
     * @property {module:interface/model/Activity}
     */
    Activity,

    /**
     * The Error model constructor.
     * @property {module:interface/model/Error}
     */
    Error,

    /**
     * The PriceEstimate model constructor.
     * @property {module:interface/model/PriceEstimate}
     */
    PriceEstimate,

    /**
     * The Product model constructor.
     * @property {module:interface/model/Product}
     */
    Product,

    /**
     * The ProductList model constructor.
     * @property {module:interface/model/ProductList}
     */
    ProductList,

    /**
     * The Profile model constructor.
     * @property {module:interface/model/Profile}
     */
    Profile,

    /**
    * The ProductsApi service constructor.
    * @property {module:interface/api/ProductsApi}
    */
    ProductsApi
};
