/**
 * Uber API
 * Move your app forward with the Uber API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Activity from './Activity';

/**
 * The Activities model module.
 * @module interface/model/Activities
 * @version 1.0.0
 */
class Activities {
    /**
     * Constructs a new <code>Activities</code>.
     * @alias module:interface/model/Activities
     */
    constructor() { 
        
        Activities.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Activities</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:interface/model/Activities} obj Optional instance to populate.
     * @return {module:interface/model/Activities} The populated <code>Activities</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Activities();

            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('history')) {
                obj['history'] = ApiClient.convertToType(data['history'], [Activity]);
            }
        }
        return obj;
    }


}

/**
 * Position in pagination.
 * @member {Number} offset
 */
Activities.prototype['offset'] = undefined;

/**
 * Number of items to retrieve (100 max).
 * @member {Number} limit
 */
Activities.prototype['limit'] = undefined;

/**
 * Total number of items available.
 * @member {Number} count
 */
Activities.prototype['count'] = undefined;

/**
 * @member {Array.<module:interface/model/Activity>} history
 */
Activities.prototype['history'] = undefined;






export default Activities;

